// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AccountLogin = { username: string, password: string, };

export type AccountRegistration = { firstname: string, middlename: string, lastname: string, username: string, password: string, confirmpassword: string, };

export type TokenVerification = { token: string, };
