// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RequestById = { id: number, };

export type ResponseWithId = { id: bigint, message: string, };
