// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Contractors = { contractor_name: string, contractor_email: string, contractor_address_street: string, contractor_address_barangay: string, contractor_address_municipality: string, contractor_address_province: string, contractor_description: string, contractor_contact_name: string, contractor_contact_position: string, contractor_contract_number: string, };

export type ReturnContractors = { id: number, contractor_name: string, contractor_email: string, contractor_address_street: string, contractor_address_barangay: string, contractor_address_municipality: string, contractor_address_province: string, contractor_description: string, contractor_contact_name: string, contractor_contact_position: string, contractor_contract_number: string, created_at: string, updated_at: string, };

export type UpdateContractorsById = { id: number, contractor_name: string, contractor_email: string, contractor_address_street: string, contractor_address_barangay: string, contractor_address_municipality: string, contractor_address_province: string, contractor_description: string, contractor_contact_name: string, contractor_contact_position: string, contractor_contract_number: string, };
