// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectTakers = { first_name: string, middle_name: string, last_name: string, profession: string, phone_number: string, };

export type ReturnProjectTakers = { id: number, first_name: string, middle_name: string, last_name: string, profession: string, phone_number: string, created_at: string, updated_at: string, };

export type UpdateProjectTakersById = { id: number, first_name: string, middle_name: string, last_name: string, profession: string, phone_number: string, };
