// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Barangays = { barangays: string, };

export type Categories = { categories: string, };

export type Incharge = { incharge: string, };

export type ProjectScope = { ps_title: string, };

export type ProjectTypes = { pt_title: string, };

export type ReturnBarangays = { id: number, barangays: string, created_at: string, updated_at: string, };

export type ReturnCategories = { id: number, categories: string, created_at: string, updated_at: string, };

export type ReturnIncharge = { id: number, incharge: string, created_at: string, updated_at: string, };

export type ReturnProjectScope = { id: number, ps_title: string, created_at: string, updated_at: string, };

export type ReturnProjectTypes = { id: number, pt_title: string, created_at: string, updated_at: string, };

export type ReturnSectors = { id: number, sectors: string, created_at: string, updated_at: string, };

export type ReturnSourceOfFunds = { id: number, sof_title: string, created_at: string, updated_at: string, };

export type ReturnSustainableDevelopmentGoals = { id: number, sdg_title: string, created_at: string, updated_at: string, };

export type ReturnUnitOfMeasurements = { id: number, um_title: string, created_at: string, updated_at: string, };

export type Sectors = { sectors: string, };

export type SourceOfFunds = { sof_title: string, };

export type SustainableDevelopmentGoals = { sdg_title: string, };

export type UnitOfMeasurements = { um_title: string, };

export type UpdateBarangaysById = { id: number, barangays: string, };

export type UpdateCategoriesById = { id: number, categories: string, };

export type UpdateInchargeById = { id: number, incharge: string, };

export type UpdateProjectScopeById = { id: number, ps_title: string, };

export type UpdateProjectTypesById = { id: number, pt_title: string, };

export type UpdateSectorsById = { id: number, sectors: string, };

export type UpdateSourceOfFundsById = { id: number, sof_title: string, };

export type UpdateSustainableDevelopmentGoalsById = { id: number, sdg_title: string, };

export type UpdateUnitOfMeasurementsById = { id: number, um_title: string, };
